### ISSUE TITLE
SSM Usage Question

### ISSUE THREAD

**Issue by harrysolovay** [sbstjn/cra-serverless#5]
Let me start by saying, what a useful and thought-provoking codebase this is! I've really enjoyed reading through and familiarizing myself with it. Quick question:

What is the utility of storing [these SSM parameters](https://github.com/sbstjn/cra-serverless/blob/master/aws/stacks/domain.ts#L67-L77)?

**Comment by sbstjn** [comment]
Those are just left-overs 🙈, or in a positive way the foundation for the typical next steps:

- Add a custom domain with Route53 and SSL Certificate (requires the CloudFront DomainName)
- Invalidate the CloudFront cache after a deployments (requires Distribution ID)

I try to store all relevant references/names/values as SSM parameters for flexible integration.

**Comment by harrysolovay** [comment]
Thank you for the explanation! 👍
